development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: poi_share_development
  host: localhost
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: poi_share_test
  host: localhost
  pool: 5
  username: root 
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: poi_share_production
  pool: 5
  host: localhost
  username: root
  password: